Add animals table
BertrandConxy/Vet-clinic-database pull request #1
Opened 2022-03-28 16:54 UTC by BertrandConxy

# Add animals table

Hello ✋,

In this branch, I have done the following:

- I created a database in the Postgre and named it `Vet_clinic`
- I created a table named `animals` and added the fields as in the requirements
- I copied the SQL codes in the schema.sql
- I inserted different data in the table and copied the SQL code into the data.sql
- I run different queries on the database animal table and copied the SQL codes into the querries.sql

2022-03-28 17:17 UTC, mmsesay requested changes
Hi @BertrandConxy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-28 17:17 UTC, mmsesay commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
- [x] You did well here. But for an instance, say an animal was born on 3 June 2019, this query won't fetch those animals right? Because it only covers animals on the 1st day and 1st Month 0f 2019. 
Please end your check on the last day and last month of the year 2019.

See example:
```sql
SELECT name FROM animals WHERE date_of_birth >= '2016/01/01' AND date_of_birth <= '2019/31/12';
```

2022-03-29 04:59 UTC, BertrandConxy commented on queries.sql
> +SELECT name FROM animals WHERE date_of_birth BETWEEN '2016-01-01' AND '2019-01-01';
Thank you very much @mmsesay. I get your point.

2022-03-29 05:08 UTC, BertrandConxy commented
The suggestions requested were applied in the recent commit made. Thank you.

2022-03-29 05:16 UTC, Meltrust approved these changes
Hi @BertrandConxy,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for correcting the date in your query, as requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-29 05:58 UTC, BertrandConxy commented
Thank you @Meltrust

2022-03-29 05:58 UTC, merged